# Generated by Django 3.1.5 on 2021-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FUNDIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('change', models.FloatField()),
                ('change_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FUNDOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('change_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='STOCK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('change', models.FloatField()),
                ('change_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WEIGHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('weight', models.FloatField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
